[tool.poetry]
name = "course-stepik-100707"
version = "0.1.0"
description = ""
authors = ["Roman Paltsev <roman.palcev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
